### ISSUE TITLE
Coverage does not update if initial coverageThreshold values are set to 0

### ISSUE THREAD

**Issue by scottkacyn** [markis/jest-ratchet#67]
To reproduce, use the following config:

```
“coverageThreshold”: {
  “global”: {
    “branches”: 0,
    “lines”: 0,
    “functions”: 0,
    “statements”: 0
  }
}
```

1. Run jest test suite
2. Check jest config

Expected result:
coverageThreshold values are ratcheted up to the actual coverage values

Actual result:
coverageThreshold values are unchanged

**Comment by markis** [comment]
Thank you for bug report!  That was a complete oversight.  In terms of jest coverage threshold, the docs specify:
> Thresholds specified as a positive number are taken to be the minimum percentage required. Thresholds specified as a negative number represent the maximum number of uncovered entities allowed.
[https://jestjs.io/docs/en/configuration#coveragethreshold-object](Source)

They don't exactly specify what 0 means, but for the sake of simplicity, I believe most use cases will use it as a percentage and not as a line coverage.  This was fixed in #66 and released in v2.0.2
